In [1]:
import numpy as np

import time

from draft import ClearEye,  BlurEye

# import tensorflow as tf

In [2]:
image = np.array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                  [0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0],
                  [0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0],
                  [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
                  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                  [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
                  ])

In [28]:
#mean_layer = tf.keras.layers.AvgPool2D((5, 5), input_shape=(1, 10, 10))

In [3]:
eye = ClearEye(clear_eye_dim=2, array_image=image)


In [4]:
eye.clear_matrix

array([[[ 0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,
          0.    ],
        [ 0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,
          0.    ],
        [ 0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,
          0.    ],
        [ 0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,
          0.    ],
        [ 0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,
          0.    ],
        [ 0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,
          0.    ],
        [ 0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,
          0.    ],
        [ 0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,
          0.    ],
        [ 0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,
          0.    ],
        [ 0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,
          0.    ],
        [ 0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,
          0.    ]]

In [5]:
eye.clear_matrix[10][10]

array([ 1.    ,  1.732 ,  1.184 ,  0.32  , -0.3662, -0.3662, -0.7324,
       -0.7324], dtype=float16)

In [8]:
box = np.array([[0, 0], [0, 1]], dtype=int)

In [9]:
eye.aggregate_box(box)

array([ 1.    ,  1.732 ,  1.184 ,  0.32  , -0.3662, -0.3662, -0.7324,
       -0.7324], dtype=float16)

In [10]:
blur_eye = BlurEye(blur_eye_dim=4, associated_clear_eye_dim=2, array_image=image, blur_factor_reduction=2)

In [11]:
blur_eye.blur_matrix

array([[[ 0.     ,  0.     ,  0.     ,  0.     ,  0.     ,  0.     ,
          0.     ,  0.     ],
        [ 0.     ,  0.     ,  0.     ,  0.     ,  0.     ,  0.     ,
          0.     ,  0.     ],
        [ 0.     ,  0.     ,  0.     ,  0.     ,  0.     ,  0.     ,
          0.     ,  0.     ],
        [ 0.     ,  0.     ,  0.     ,  0.     ,  0.     ,  0.     ,
          0.     ,  0.     ],
        [ 0.     ,  0.     ,  0.     ,  0.     ,  0.     ,  0.     ,
          0.     ,  0.     ],
        [ 0.     ,  0.     ,  0.     ,  0.     ,  0.     ,  0.     ,
          0.     ,  0.     ],
        [ 0.     ,  0.     ,  0.     ,  0.     ,  0.     ,  0.     ,
          0.     ,  0.     ],
        [ 0.     ,  0.     ,  0.     ,  0.     ,  0.     ,  0.     ,
          0.     ,  0.     ],
        [ 0.     ,  0.     ,  0.     ,  0.     ,  0.     ,  0.     ,
          0.     ,  0.     ],
        [ 0.     ,  0.     ,  0.     ,  0.     ,  0.     ,  0.     ,
          0.     ,  0.     ],
        [ 

In [22]:
eye.clear_matrix[4][6]

array([0., 0., 0., 0., 0., 0., 0., 0.], dtype=float16)

In [24]:
blur_eye.blur_matrix[3][6]

array([ 0.25   ,  0.433  ,  0.296  ,  0.08   , -0.09155,  0.09155,
       -0.1831 ,  0.1831 ], dtype=float16)